FROM debian:bullseye

ENV HOME=/root
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update

RUN apt-get -y dist-upgrade

RUN apt-get -y --no-install-recommends install \
    build-essential \
    ca-certificates \
    curl \
    doxygen \
    g++ \
    gdb \
    git \
    gnupg \
    gpg \
    less \
    ninja-build \
    pkg-config \
    software-properties-common \
    sudo \
    wget

# Add the public key for the llvm repository
RUN bash -c 'wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|apt-key add -'
RUN apt-add-repository -y 'deb http://apt.llvm.org/bullseye/ llvm-toolchain-bullseye-15 main'
RUN apt-add-repository -y 'deb https://archive.debian.org/debian bullseye-backports main'

RUN apt-get update

RUN apt-get -y --no-install-recommends install -t llvm-toolchain-bullseye-15 \
    clang-15 \
    clang-tidy-15 \
    clang-format

RUN apt-get -y --no-install-recommends install -t bullseye-backports \
    cmake

# Install appimage-builder
RUN mkdir -p ${HOME}/opt/src
RUN apt-get install fakeroot libgtk-3-bin squashfs-tools -y
RUN apt install python3-pip python3-venv -y
RUN pip install -U pip setuptools
RUN pip install urllib3==1.26.12 requests==2.26.0
RUN cd ${HOME}/opt/src && \
    git clone -b viam-2025-07-22 https://github.com/viamrobotics/appimage-builder.git && \
    cd appimage-builder && \
    pip install ./

# Install docker
RUN apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
RUN echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
    $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
RUN apt-get -y update
RUN apt-get -y install docker-ce docker-ce-cli containerd.io
