name: Build Latest

on:
  push:
    branches: [ main, dev, RSDK-2895 ]
    paths-ignore:
      - 'README.md'

  appimage:
    name: AppImage Build
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: [buildjet-2vcpu-ubuntu-2204-arm]
            image: ghcr.io/viamrobotics/canon:arm64-cache
            platform: linux/arm64
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
