name: Build Latest

on:
  push:
    branches: [ main, dev, RSDK-2895 ]
    paths-ignore:
      - 'README.md'

jobs:
  appimage:
    name: AppImage Build
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: [ubuntu-latest]
            image: ghcr.io/viamrobotics/canon:amd64-cache
            platform: linux/amd64
          - arch: [buildjet-2vcpu-ubuntu-2204-arm]
            image: ghcr.io/viamrobotics/canon:arm64-cache
            platform: linux/arm64
    runs-on: ${{ matrix.arch }}
    container:
      image: ${{ matrix.image }}
      options: --platform ${{ matrix.platform }}
    timeout-minutes: 15
    outputs:
      date: ${{ steps.build_date.outputs.date }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Clean build artifacts
        run: make clean
      - name: Build cmake and appimage
        uses: docker/build-push-action@v4
        with:
          context: .
          file: etc/Dockerfile.mod.jetson
          tags: viam-csi-mod:0.0.1
          build-args: |
            HUB_USER=seanpollock
            BASE_TAG=0.0.1
            BASE_NAME=viam-cpp-jetson
        
