name: Build Latest

on:
  push:
    branches: [ main, dev, RSDK-2895 ]
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, arm64]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
