name: Build Latest

on:
  push:
    branches: [ main, dev, RSDK-2895 ]
    paths-ignore:
      - 'README.md'

jobs:
  appimage:
    name: AppImage Build
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: [buildjet-2vcpu-ubuntu-2204-arm]
            image: ghcr.io/seanavery/viam-cpp-jetson:0.0.1
            platform: linux/arm64
    runs-on: ${{ matrix.arch }}
    container:
      image: ${{ matrix.image }}
      options: --platform ${{ matrix.platform }}
    timeout-minutes: 15
    outputs:
      date: ${{ steps.build_date.outputs.date }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Clean build artifacts
        run: make clean
      - name: Build binary with cmake 
        run: make build
     - name: Build appimage with appimage-builder
        run: make package
        
